### ISSUE TITLE
Move styled-components to be peer dependency

### ISSUE THREAD

**Issue by tienpham94** [tienpham94/react-awesome-spinners#2]

**Comment by tienpham94** [comment]
Fixed

**Comment by maxsbelt** [comment]
Hi @tienpham94. Seems like `styled-components` is still presented in [`dependencies` section](https://github.com/tienpham94/react-awesome-spinners/blob/master/package.json#L89). I think it should be moved in `devDependencies` section instead.

**Comment by tienpham94** [comment]
Hi @maxsbelt, thank you for noticing! I somehow missed that, will remove asap in the next release!

**Comment by ezengold** [comment]
Hi. I still get an error of version about `styled-components`. In my project, I have `styled-components^5.2.3` but when trying to install `react-awesome-spinners^1.3.1`, i get this error:
<img width="621" alt="Screen Shot 2022-02-07 at 16 06 47" src="https://user-images.githubusercontent.com/58929033/152814308-c9037346-fe34-4c51-a998-b305d2631725.png">
